plugins:
  - id: configuration-as-code
  - id: configuration-as-code-support
  - id: job-dsl
  - id: git
  - id: git-client
  - id: github
  - id: github-branch-source
  - id: workflow-aggregator
  - id: pipeline-stage-view
  - id: pipeline-graph-analysis
  - id: pipeline-utility-steps
  - id: docker-workflow
  - id: docker-commons
  - id: credentials
  - id: credentials-binding
  - id: plain-credentials
  - id: ssh-credentials
  - id: cloudbees-folder
  - id: junit
  - id: htmlpublisher
  - id: matrix-auth
  - id: role-strategy
  - id: timestamper
  - id: build-timeout
  - id: ws-cleanup
  - id: ansicolor