---
- name: Apply common base config to all jenkins nodes
  hosts: _master,_agent
  become: yes

  roles:
    - common

- name: Configure Jenkins master base (Docker)
  hosts: _master
  become: yes

  roles:
    - jenkins_master

- name: Configure Jenkins agent node
  hosts: _agent
  become: yes

  roles:
    - jenkins_agent